posts/urls.py
from django.urls import path
from .views import post_list ,post_detail,new_post,edit_post,delete_post

app_name='posts'

urlpatterns = [
    path('', post_list,name='post_list'),
    path('<int:id>', post_detail,name='post_detail'),
    path('new' , new_post,name='new_post'),
    path('<int:id>/edit', edit_post ,name="edit_post"),
    path('<int:id>/delete', delete_post ,name="delete_post")

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace="posts")),
   
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_user")
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=5000)
    img = models.ImageField(upload_to="posts/", null=True , blank=True)
    active = models.BooleanField(default=False)
  
    def __str__(self):
        return self.title 

posts/forms.py
from django import forms 

from .models import Posts


class Postfrom(forms.ModelForm):
    class Meta :
        model = Posts
        # fields = '__all__'
        # fields = ['active','img','content','title']
        exclude =['author']

posts/views.py
from django.shortcuts import render ,redirect
from .models import Posts 
from .forms import Postfrom
from django.urls import reverse

# Create your views here.

def post_list(request):
    objects = Posts.objects.all()
    return render(request,'posts/post_list.html',{"posts":objects})


def post_detail(request , id):
    single = Posts.objects.get(id=id)
    return render(request,'posts/post_detail.html',{"posts":single})

def new_post(request):
    if request.method == "POST":
        form = Postfrom(request.POST , request.FILES)
        if form.is_valid():
           my_form = form.save(commit=False)
           my_form.author = request.user
           my_form.save()
           return redirect(reverse('posts:post_list'))
       
    else:
        form = Postfrom
    return render(request,'posts/new.html',{'form':form})
    
    
    

def edit_post(request,id):
    single = Posts.objects.get(id=id)
    if request.method == "POST":
        form = Postfrom(request.POST , request.FILES ,instance=single)
        if form.is_valid():
            form.save()
    else:
        form = Postfrom(instance=single)
    return render(request,'posts/edit.html',{'form':form})
       
     
     
def delete_post(request,id):
    single = Posts.objects.get(id=id)
    single.delete()
    return redirect(reverse('posts:post_list'))

posts/templates/posts/edit.html
<h1> edit post </h1>


<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="save">
</form>

posts/templates/posts/new.html
<h1> create post </h1>


<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="create">
</form>

posts/templates/posts/post_detail 2.html
<h2>post ditail</h2>

<h3>{{Posts}}</h3>
<p>{{post.content}} </p>

<img src="{{posts.img.url}}" alt="">


<hr>

<a href="{% url 'posts:edit_post' posts.id %}" > edit_post  </a>
<a href="{% url 'posts:delete_post' posts.id %}" > delete_post  </a>

posts/templates/posts/posts.html
<h1>Blog </h1>

<a href="{%url 'posts:new_post'%}">Create New Post</a>
{% for post in posts %}

    <h2> <a href="{%url 'posts:post_detail' post.id %}">{{posts}}   </a> </h2>

    {% endfor %}

templates/base.html
{%load static%}

<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html>

<head>
    <meta charset="utf-8">
    <title>Galaxy - Personal Blog Template</title>

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1 ">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1 ">

    <!-- theme meta -->
    <meta name="theme-name" content="galaxy" />

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{%static 'plugins/bootstrap/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'plugins/fontawesome/css/all.css'%}">

    <!-- Main Stylesheet -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">

    <!--Favicon-->
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <link rel="icon" href="images/favicon.png" type="image/x-icon">

</head>

<body>
    <!-- START preloader-wrapper -->
    <div class="preloader-wrapper">
        <div class="preloader-inner">
            <div class="spinner-border text-red"></div>
        </div>
    </div>
    <!-- END preloader-wrapper -->

    <!-- START main-wrapper -->
    <section class="d-flex">

        <!-- start of sidenav -->
        <aside>
            <div class="sidenav position-sticky d-flex flex-column justify-content-between">
                <a class="navbar-brand" href="index.html" class="logo">
                    <img src="images/logo.png" alt="">
                </a>
                <!-- end of navbar-brand -->

                <div class="navbar navbar-dark my-4 p-0 font-primary">
                    <ul class="navbar-nav w-100">
                        <li class="nav-item active">
                            <a class="nav-link text-white px-0 pt-0" href="index.html">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-white px-0" href="about.html">About</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-white px-0" href="contact.html">Contact</a>
                        </li>
                        <li class="nav-item  accordion">
                            <div id="drop-menu" class="drop-menu collapse">
                                <a class="d-block " href="index-2.html">Home 2</a>
                                <a class="d-block " href="category.html">Category</a>
                                <a class="d-block " href="post-details.html">Post Details</a>
                                <a class="d-block " href="privacy.html">Privacy &amp; Policy</a>
                            </div>
                            <a class="nav-link text-white" href="#!" role="button" data-toggle="collapse"
                                data-target="#drop-menu" aria-expanded="false" aria-controls="drop-menu">Pages</a>
                        </li>
                        <li class="nav-item mt-3">
                            <select class="custom-select bg-transparent rounded-0 text-white shadow-none"
                                id="pick-lang">
                                <option selected value="en">English</option>
                                <option value="fr">French</option>
                            </select>
                        </li>
                    </ul>
                </div>
                <!-- end of navbar -->

                <ul class="list-inline nml-2">
                    <li class="list-inline-item">
                        <a href="#!" class="text-white text-red-onHover pr-2">
                            <span class="fab fa-twitter"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!" class="text-white text-red-onHover p-2">
                            <span class="fab fa-facebook-f"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!" class="text-white text-red-onHover p-2">
                            <span class="fab fa-instagram"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!" class="text-white text-red-onHover p-2">
                            <span class="fab fa-linkedin-in"></span>
                        </a>
                    </li>
                </ul>
                <!-- end of social-links -->
            </div>
        </aside>
        <!-- end of sidenav -->

        {% block body %}
        
        {% endblock body %}

    </section>
    <!-- END main-wrapper -->

    <!-- All JS Files -->
    <script src="{% static 'plugins/jQuery/jquery.min.js'%}"></script>
    <script src="{%static 'plugins/bootstrap/bootstrap.min.js'%}"></script>

    <!-- Main Script -->
    <script src="{%static 'js/script.js'%}"></script>
</body>

</html>